# Generated by Django 3.1.5 on 2021-01-30 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20210130_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='authentication.authuser'),
            preserve_default=False,
        ),
    ]
