# Generated by Django 3.1.5 on 2021-01-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_vacancies', to='profiles.PersonProfile'),
        ),
    ]
