# Generated by Django 3.1.5 on 2021-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
        ('jobs', '0002_auto_20210131_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='vacancies', to='taxonomies.Tag'),
        ),
    ]
