# Generated by Django 3.1.5 on 2021-01-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210130_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'verbose_name_plural': 'application statuses'},
        ),
    ]
