# Generated by Django 3.1.5 on 2021-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('jobs', '0003_auto_20210208_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, related_name='applied_vacancies', through='jobs.Application', to='profiles.PersonProfile'),
        ),
    ]
