# Generated by Django 3.1.5 on 2021-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210130_1301'),
        ('jobs', '0003_auto_20210130_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_vacancies', to='profiles.PersonProfile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(related_name='applied_vacancies', through='jobs.Application', to='profiles.PersonProfile'),
        ),
    ]
