# Generated by Django 3.1.5 on 2021-01-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
    ]
